object ShowIt: TShowIt
  Left = 275
  Top = 10
  BorderStyle = bsNone
  Caption = 'ShowIt'
  ClientHeight = 645
  ClientWidth = 1107
  Color = clBtnFace
  TransparentColor = True
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  Position = poDesigned
  OnMouseMove = FormMouseMove
  OnPaint = FormPaint
  PixelsPerInch = 96
  TextHeight = 13
end
